In [42]:
%display latex
reset()

# 1. Vetores e matrizes

#### Vetores e estrutura
Vetores são constrídos pelo comando vector, com sintaxe `vector([x1,x2,x3,...,xn])`

In [73]:
v = vector([x,x^8,5])
v[0]

x

In [46]:
print(parent(v))

Vector space of dimension 3 over Symbolic Ring


#### Soma, multiplicação escalar e produto vetorial

In [47]:
w=vector([5,2,1])

In [48]:
v.cross_product(w)

(x^8 - 10, -x + 25, -5*x^8 + 2*x)

Produto interno

In [49]:
w*v

2*x^8 + 5*x + 5

In [50]:
v.dot_product(w)

2*x^8 + 5*x + 5

Também é possível plotar vetores

In [53]:
plot(w, color = 'red', thickness = 1.5, frame=True)

Graphics3d Object

Hermitiano

In [54]:
var('y', domain='real')

y

In [56]:
z = vector([I*2,x,y]);z

(2*I, x, y)

In [57]:
z*w

2*x + y + 10*I

In [58]:
z.hermitian_inner_product(w)

y + 2*conjugate(x) - 10*I

Norma

In [59]:
w.norm()

sqrt(30)

In [60]:
z.norm()

sqrt(y^2 + abs(x)^2 + 4)

#### Matrizes

In [74]:
a = matrix([[1,2,3],[5,23,8],[8,5,1]]);a

[ 1  2  3]
[ 5 23  8]
[ 8  5  1]

In [77]:
a[0][1] *2

4

In [64]:
a.transpose()

[ 1  5  8]
[ 2 23  5]
[ 3  8  1]

In [17]:
z*a

(5*x + 8*y + 2*I, 23*x + 5*y + 4*I, 8*x + y + 6*I)

#### Matrizes especiais


In [18]:
matrix.zero(5,10)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]

In [19]:
matrix.identity(4)

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]

In [20]:
matrix.ones(3)

[1 1 1]
[1 1 1]
[1 1 1]

In [21]:
d = matrix.diagonal([y,y,y^2]);d

[  y   0   0]
[  0   y   0]
[  0   0 y^2]

#### Determinante, traço, transposta, inversa, conjugada

In [22]:
d.det()

y^4

In [23]:
d.trace()

y^2 + 2*y

In [24]:
d.transpose()

[  y   0   0]
[  0   y   0]
[  0   0 y^2]

In [25]:
d.conjugate()

[  y   0   0]
[  0   y   0]
[  0   0 y^2]

In [26]:
d.inverse()

[   1/y      0      0]
[     0    1/y      0]
[     0      0 y^(-2)]

Resolver equações matriciais é fácil usando o método `solve_right`. Calculando `A.solve_right(Y)` obtém-se uma matrix (ou vetor) **X** tal que **AX=Y**

Resolvendo o sistema linear
\begin{equation}
\left\{ \begin{array}{ccc}  2x + y -z = 3\\ x+3y+2z = 4 \\ 3x -2y+z = -5 \end{array} \right.
\end{equation}

In [27]:
coef = matrix([(2,1,-1),(1,3,2),(3,-2,1)]);coef

[ 2  1 -1]
[ 1  3  2]
[ 3 -2  1]

In [28]:
resul = vector([3,4,-5]);resul

(3, 4, -5)

In [29]:
X = coef.solve_right(resul);X

(0, 2, -1)

#### Transformação linear

In [66]:
T = linear_transformation(a); T

Vector space morphism represented by the matrix:
[ 1  2  3]
[ 5 23  8]
[ 8  5  1]
Domain: Vector space of dimension 3 over Rational Field
Codomain: Vector space of dimension 3 over Rational Field

In [67]:
T([1,1,1])

(14, 30, 12)

In [68]:
T.is_bijective()

True

#### Autovalores, auto vetores e diagonalização

In [32]:
d.charpoly()

x^3 + (-y^2 - 2*y)*x^2 + (2*y^3 + y^2)*x - y^4

In [33]:
a.eigenvalues()

[-4.089163512470301?, 3.608654158617636?, 25.48050935385267?]

In [34]:
a.eigenvectors_right()

[(-4.089163512470301?, [(1, 0.3939680825482897?, -1.959033225855627?)], 1),
 (3.608654158617636?, [(1, -0.8505050826211235?, 1.436554774619961?)], 1),
 (25.48050935385267?, [(1, 8.99446803455560?, 2.163857761580494?)], 1)]

In [69]:
k = matrix([[1,1,-3],[0,4,0],[-3,3,1]])
k

[ 1  1 -3]
[ 0  4  0]
[-3  3  1]

In [70]:
k.charpoly()

x^3 - 6*x^2 + 32

In [71]:
k.eigenvectors_right()

[(-2,
  [
  (1, 0, 1)
  ],
  1),
 (4,
  [
  (1, 0, -1)
  ],
  2)]